# scripts/setup_env.ps1
# One-shot secure setup of API keys into local .env file.
# Keys are typed with -AsSecureString so they never appear on screen or in history.

[CmdletBinding()]
param()

$envPath = Join-Path $PSScriptRoot "..\.env"
if (Test-Path $envPath) {
    Write-Host "[!] .env already exists. Skipping (delete it first to re-run)." -ForegroundColor Yellow
    exit 0
}

function Read-Secret([string]$prompt) {
    Write-Host $prompt -NoNewline
    $secure = Read-Host -AsSecureString
    $ptr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

$deepseek = Read-Secret "Enter your DEEPSEEK_API_KEY (input hidden): "
$minimax  = Read-Secret "Enter your MiniMax_API_KEY    (input hidden): "

$content = @"
# AIDD Multi-Agent - Local secrets (DO NOT COMMIT)
# Generated by scripts/setup_env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm")

DEEPSEEK_API_KEY=$deepseek
MiniMax_API_KEY=$minimax
"@

Set-Content -Path $envPath -Value $content -Encoding UTF8
Write-Host "[OK] .env created. Keys stored locally only." -ForegroundColor Green
Write-Host "[OK] .env is in .gitignore, will not be pushed." -ForegroundColor Green
Write-Host ""
Write-Host "Next: rotate (revoke) the old keys in their respective web consoles," -ForegroundColor Yellow
Write-Host "      because they were exposed in chat history." -ForegroundColor Yellow