# scripts/setup_env.ps1
# Robust setup for API keys. Asks twice, validates length, refuses to write
# empty values, refuses to overwrite without confirmation.
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup_env.ps1

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$envPath = Join-Path $PSScriptRoot "..\.env"
$MIN_LEN = 20   # API keys are 40+ chars; reject anything shorter

# ---------- helpers ----------

function Read-VisibleKey([string]$prompt) {
    """Read a key visibly (so user can verify what they typed) and return it.
    Disables PSReadLine history to avoid key being saved in history.
    """
    if (Get-Command Set-PSReadLineOption -ErrorAction SilentlyContinue) {
        Set-PSReadLineOption -HistorySaveStyle SaveNothing | Out-Null
    }
    $value = Read-Host $prompt
    return $value.Trim()
}

function Confirm-Overwrite([string]$path) {
    if (-not (Test-Path $path)) { return $true }
    $ans = Read-Host "  .env already exists. Overwrite? [y/N]"
    return ($ans -match "^[yY]")
}

# ---------- main ----------

Write-Host ""
Write-Host "=== AIDD Multi-Agent: API key setup ===" -ForegroundColor Cyan
Write-Host "Keys will be written to .env (gitignored, local only)."
Write-Host ""

if (-not (Confirm-Overwrite $envPath)) {
    Write-Host "[skip] .env preserved." -ForegroundColor Yellow
    exit 0
}

# Loop until both keys are valid
while ($true) {
    $deepseek = Read-VisibleKey "  Enter DEEPSEEK_API_KEY (will be visible so you can verify): "
    $minimax  = Read-VisibleKey "  Enter MiniMax_API_KEY (visible): "

    Write-Host ""
    Write-Host "  DEEPSEEK length: $($deepseek.Length)"
    Write-Host "  MiniMax  length: $($minimax.Length)"
    Write-Host ""

    $ds_ok = $deepseek.Length -ge $MIN_LEN
    $mm_ok = $minimax.Length  -ge $MIN_LEN

    if ($ds_ok -and $mm_ok) { break }

    Write-Host "[!] One or both keys look too short (min $MIN_LEN chars)." -ForegroundColor Yellow
    $retry = Read-Host "  Retry? [Y/n]"
    if ($retry -match "^[nN]") { exit 1 }
    Write-Host ""
}

# Write file
$content = @"
# AIDD Multi-Agent - Local secrets (DO NOT COMMIT)
# Generated by scripts/setup_env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm")

DEEPSEEK_API_KEY=$deepseek
MiniMax_API_KEY=$minimax
"@
Set-Content -Path $envPath -Value $content -Encoding UTF8

Write-Host "[OK] .env written at $envPath" -ForegroundColor Green
Write-Host "[OK] .env is gitignored, will NOT be pushed."
Write-Host ""
Write-Host "  IMPORTANT:" -ForegroundColor Yellow
Write-Host "  - Clear clipboard: 'hello' | Set-Clipboard"
Write-Host "  - Clear PS history: Remove-Item (Get-PSReadLineOption).HistorySavePath -ErrorAction SilentlyContinue"
Write-Host "  - Rotate the keys at provider consoles if they were ever pasted in chat."