"""scripts/setup_env.py - Securely set up API keys via Python input().

Why Python instead of PowerShell Read-Host?
- PowerShell -AsSecureString returns empty in some terminals
- Python input() works reliably everywhere
- The key is shown so you can verify it was typed correctly
- This file is never touched after setup

Usage:
    python scripts/setup_env.py
"""
import os
import sys
from pathlib import Path

ENV_PATH = Path(__file__).parent.parent / ".env"
MIN_LEN = 20


def main():
    print()
    print("=== AIDD Multi-Agent: API key setup ===")
    print("Keys will be written to .env (gitignored, local only).")
    print("Keys ARE visible as you type so you can verify correctness.")
    print()
    print("  Only MiniMax is active by default (see config.yaml).")
    print("  DeepSeek is supported by the harness but disabled; pass --with-deepseek")
    print("  to also collect a DeepSeek key.")
    print()

    with_deepseek = "--with-deepseek" in sys.argv

    # Optional: confirm overwrite
    if ENV_PATH.exists():
        ans = input(f"  .env already exists. Overwrite? [y/N]: ").strip().lower()
        if ans != "y":
            print("[skip] .env preserved.")
            return 0

    while True:
        minimax = input("  Enter MiniMax_API_KEY:    ").strip()
        deepseek = ""
        if with_deepseek:
            deepseek = input("  Enter DEEPSEEK_API_KEY: ").strip()
        print()
        print(f"  MiniMax  length: {len(minimax)}")
        if with_deepseek:
            print(f"  DEEPSEEK length: {len(deepseek)}")
        print()

        minimax_ok = len(minimax) >= MIN_LEN
        deepseek_ok = (not with_deepseek) or (len(deepseek) >= MIN_LEN)
        if minimax_ok and deepseek_ok:
            break

        print(f"[!] One or both keys are too short (min {MIN_LEN} chars).")
        ans = input("  Retry? [Y/n]: ").strip().lower()
        if ans == "n":
            print("[abort]")
            return 1
        print()

    content = (
        "# AIDD Multi-Agent - Local secrets (DO NOT COMMIT)\n"
        f"# Generated by scripts/setup_env.py\n"
        "\n"
        f"MiniMax_API_KEY={minimax}\n"
    )
    if with_deepseek:
        content += f"DEEPSEEK_API_KEY={deepseek}\n"
    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"[OK] .env written at {ENV_PATH}")
    print("[OK] .env is gitignored, will NOT be pushed.")
    print()
    print("  IMPORTANT:")
    print("  - Clear clipboard:  echo hello | clip")
    print("  - Clear PS history: Remove-Item (Get-PSReadLineOption).HistorySavePath -EA SilentlyContinue")
    print("  - Rotate keys at provider consoles if they were ever pasted in chat.")
    return 0


if __name__ == "__main__":
    sys.exit(main())